/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdio.h>
#include <stdint.h>
#include "main.h"
#include "builtin_leds.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint32_t psp_of_task[MAX_TASK] = { T1_STACK_START, T2_STACK_START,T3_STACK_START, T4_STACK_START };

uint32_t task_handlers[MAX_TASK];

uint32_t current_task = 0;

int main(void) {

	enable_processor_faults();

	int_scheduler_stack(SCHED_STACK_START);

	task_handlers[0] = (uint32_t) task1_handler;
	task_handlers[1] = (uint32_t) task2_handler;
	task_handlers[2] = (uint32_t) task3_handler;
	task_handlers[3] = (uint32_t) task4_handler;

	init_task_stack();

	led_init_all();

	init_systic_timer(TICK_HZ);

	switch_sp_to_psp();

	task1_handler();

}
void init_systic_timer(uint32_t tick_hz) {
	uint32_t *pSRVR = (uint32_t*) 0xE000E014;
	uint32_t *pSCSR = (uint32_t*) 0xE000E010;

	uint32_t count_value = SYSTIC_TIM_CLOCK / tick_hz;

	//Clear the value of SVR
	*pSRVR &= ~(0x00FFFFFFFF);

	//load the value in to SVR
	*pSRVR |= count_value;

	//have to do some settings
	*pSCSR |= (1 << 1); //enables the systick exceptions request
	*pSCSR |= (1 << 2); //indicated the clock source. Processor clock source

	//enables the systick
	*pSCSR |= (1 << 0); //enable the counter

}

__attribute__((naked)) void int_scheduler_stack(uint32_t sched_top_of_stack) {
	__asm volatile ("MSR MSP,%0": : "r" (sched_top_of_stack) : );
	__asm volatile ("BX LR");

}

void save_psp_value(uint32_t current_psp_value){
	psp_of_task[current_task] = current_psp_value;
}

void update_next_task(void){
	current_task++;
	current_task %= MAX_TASK;
}

uint32_t get_psp_value(void)
{
	return psp_of_task[current_task];
}

void init_task_stack(void) {

	uint32_t *pPSP;
	for (int i = 0; i < MAX_TASK; i++) {
		pPSP = (uint32_t*) psp_of_task[i];
		pPSP--;
		*pPSP = DUMMY_XPSR; //0x01000000

		pPSP--; //pc
		*pPSP = task_handlers[i];

		pPSP--; //LR
		*pPSP = 0xFFFFFFFD;

		for (int j = 0; j < 13; j++) {
			pPSP--;
			*pPSP = 0;
		}

		psp_of_task[i] = (uint32_t) pPSP;

	}
}

void enable_processor_faults(void) {

	uint32_t *pSHCSR = (uint32_t*) 0xE000ED24;

	*pSHCSR |= (1 << 16); //mem manage
	*pSHCSR |= (1 << 17); //bus manage
	*pSHCSR |= (1 << 18); //usage manage

}

__attribute__((naked)) void SysTick_Handler(void) {

	/*Save the context of current task */

	//1. Get current running task's PSP value
	__asm volatile("MRS R0,PSP");

	//2. Using that PSP value store SF2( R4 to R11)
	__asm volatile("STMDB R0!,{R4-R11}");

	__asm volatile("PUSH {LR}");

	//3. Save the current value of PSP
    __asm volatile("BL save_psp_value");



	/*Retrieve the context of next task */

	//1. Decide next task to run
    __asm volatile("BL update_next_task");

	//2. get its past PSP value
	__asm volatile ("BL get_psp_value");

	//3. Using that PSP value retrieve SF2(R4 to R11)
	__asm volatile ("LDMIA R0!,{R4-R11}");

	//4. update PSP and exit
	__asm volatile("MSR PSP,R0");

	__asm volatile("POP {LR}");

	__asm volatile("BX LR");;
}

void task1_handler(void) {

	while (1) {
		led_on(LED_GREEN);
		delay(DELAY_COUNT_1S);
		led_off(LED_GREEN);
		delay(DELAY_COUNT_1S);
	}
}
void task2_handler(void) {
	while (1) {
		led_on(LED_ORANGE);
		delay(DELAY_COUNT_500MS);
		led_off(LED_ORANGE);
		delay(DELAY_COUNT_500MS);

	}
}
void task3_handler(void) {

	while (1) {
		led_on(LED_BLUE);
		delay(DELAY_COUNT_250MS);
		led_off(LED_BLUE);
		delay(DELAY_COUNT_250MS);

	}
}
void task4_handler(void) {

	while (1) {
		led_on(LED_RED);
		delay(DELAY_COUNT_125MS);
		led_off(LED_RED);
		delay(DELAY_COUNT_125MS);

	}
}



__attribute__((naked)) void switch_sp_to_psp(void){

	//1. initialize the psp with TASK1 stack start address

	//get the value of psp of current task
	__asm volatile("PUSH {LR}");//preseve LR which connect us back to main
	__asm volatile("BL get_psp_value");
	__asm volatile("MSR PSP,R0");//initialize PSP
	__asm volatile("POP {LR}");

	//2. Change sp to psp using control register
	__asm volatile("MOV R0,#0x02");
	__asm volatile("MSR CONTROL,R0");

	__asm volatile("BX LR");



}


// implement the fault handlers
void HardFault_Handler(void) {
	printf("Exception : Hardfault\n");
	while (1)
		;
}

void MemManage_Handler(void) {
	printf("Exception : MemManage\n");
	while (1)
		;
}

void BusFault_Handler(void) {
	printf("Exception : BusFault\n");
	while (1)
		;
}
